### ISSUE TITLE
just some questions :3

### ISSUE THREAD

**Issue by KiernanTheFemboy** [JesseWx2011/Intellistar#1]
Haii, I decided to try out your IS1 simulator and just decided to ask a few questions,

1. do you plan on making the slides automatic so that we don't have to press the next slide button?
2. do you plan on making the radar animate?
3. do you plan on adding configuration for adding different slides such as air quality or traffic?

that's all i have to ask... For now hehe :3

**Comment by JesseWx2011** [comment]
Hello @KiernanTheFemboy, thanks for your feedback. 

Q1: I will attempt to make them automatic. 

Q2: I had to use another company's system of the radar that is not animated. I will try the Weather Channel though. So again, I will attempt that as well.

Q3: I don't plan to do traffic, but I will probably do Air Quality.

**Comment by KiernanTheFemboy** [comment]
Oki, btw are you Hastytube? If so I'm The KSG Channel, Idk if you remember me :3

**Comment by JesseWx2011** [comment]
No, I am not HastyTube.

**Comment by KiernanTheFemboy** [comment]
Oh, sorry for any confusion.
