### ISSUE TITLE
Zipcodes

### ISSUE THREAD

**Issue by Halloween20** [JesseWx2011/Intellistar#2]
Can you the zipcode bar for me to see my location ?

**Comment by JesseWx2011** [comment]
Hello Halloween20! Sorry for the late response. Most of the configuration is in the config.js file in the js folder. I will add an option for zip code or lat/long in the js folder. Thanks for your suggestion! Well appreciated.

**Comment by JesseWx2011** [comment]
Hmm, sorry for the delay, but what do you mean by seeing your location?

**Comment by JesseWx2011** [comment]
Oh, you simply have to go to the config.js file in js, and go to https://www.google.com/maps, right click on your mousepad or mouse, and click the coordinates. Watch this video: https://drive.google.com/file/d/1BDp5AF5nhR0LNJ1Uwr7db4ruNGm-JMCh/view?usp=sharing
